name: graphs

dependencies:
- matplotlib>=3.5.1
- networkx>=2.6.3
- numpy>=1.22.3
- pandas>=1.3.4
- plotly>=5.7.0
- pip
- pip:
  - graphviz==0.20
  - IPython==8.2.0
  - pydot==1.4.2
  - schemdraw==0.14




